# -*- coding: utf-8 -*-
"""Chương1_DTH235694.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SRuCwJrughwGvo3zHcK224OsNoE6uRPi
"""

#Chuong trinh tinh tong 2 so
so1 = int(input("Nhap so thu nhat: "))
so2 = int(input("Nhap so thu hai: "))

#Tinh tong
tong = so1 + so2

print("Tong hai so la: ",tong)

#Nhập Tên
name = input("Nhap ten cua ban: ")
print("Xin chao",name)

#Xuất tên tuổi chiều cao
name = "John"
age = 25
height = 1.75
print("Tên: ",name)
print("Tuổi: ",age)
print("Chiều cao: ",height)

#Tính căn bậc 2
import math
number = 16
square_root = math.sqrt(number)

print("Cân bậc hai của", number ,"là ",square_root)